<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <PackageJsonName Condition="$(PackageJsonName) == ''">mynuxtapp-web</PackageJsonName>
    <PackageJsonPrivate Condition="$(PackageJsonPrivate) == ''">true</PackageJsonPrivate>
    <PackageJsonType Condition="$(PackageJsonType) == ''">module</PackageJsonType>
    <PackageJsonScriptsBuild Condition="$(PackageJsonScriptsBuild) == ''">nuxt build</PackageJsonScriptsBuild>
    <PackageJsonScriptsDev Condition="$(PackageJsonScriptsDev) == ''">nuxt dev</PackageJsonScriptsDev>
    <PackageJsonScriptsGenerate Condition="$(PackageJsonScriptsGenerate) == ''">nuxt generate</PackageJsonScriptsGenerate>
    <PackageJsonScriptsPreview Condition="$(PackageJsonScriptsPreview) == ''">nuxt preview</PackageJsonScriptsPreview>
    <PackageJsonScriptsPostinstall Condition="$(PackageJsonScriptsPostinstall) == ''">nuxt prepare</PackageJsonScriptsPostinstall>
    <PackageJsonDependenciesNuxt Condition="$(PackageJsonDependenciesNuxt) == ''">^3.20.2</PackageJsonDependenciesNuxt>
    <PackageJsonDependenciesVue Condition="$(PackageJsonDependenciesVue) == ''">^3.5.25</PackageJsonDependenciesVue>
    <PackageJsonDependenciesVueRouter Condition="$(PackageJsonDependenciesVueRouter) == ''">^4.6.4</PackageJsonDependenciesVueRouter>
  </PropertyGroup>
</Project>